name: tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/*.scad'
      - .github/workflows/tests.yaml

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Test
      run: |
        make test
